# use base image
FROM node:24.1-bookworm-slim

# set up working directory 
WORKDIR /app

# copy project files
# COPY requirements.txt .

# install dependencies


# command to run
CMD [ "npm", "start", "--prefix", "/app/frontend" ]